version: "3.7"
services:
  make-my-day:
    container_name: make-my-day
    build:
      context: .
    networks:
      - default
    ports:
      - 8000:8000
    volumes:
      - .:/var/app
      - /var/app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: true
    env_file:
      - .env
volumes:
  make-my-day:
