version: "3.7"
services:
  make-my-day:
    build:
      context: .
    networks:
      - default
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
volumes:
  make-my-day:
